### ISSUE TITLE
[API] Handle Jakarta EE @Inject

### ISSUE THREAD

**Issue by theo-malka** [noleme/noleme-vault#95]
As part of Spring-boot 3 update, it is required to switch from Java EE to Jakarta EE 9 specification.
This breaks @Inject field annotations we are using in various part of our app.

It could be interesting to accept the 2 annotations, which would be in the `VaultLegacyCompiler.java` something like:

```java
if (c.isAnnotationPresent(javax.inject.Inject.class) || (c.isAnnotationPresent(jakarta.inject.Inject.class))
{
    ...doStuff
}
```

**Comment by eledhwen** [comment]
Thinking about it again, in this case your initial suggestion would probably be more appropriate as a first move, excluding class loading shenanigans I cannot think of a reasonable setup where this scenario would cause issues.

You can make a PR or I'll do it when I can get time in front of a computer.
